---
version: 2
before:
  hooks:
    - go mod download
builds:
  - id: "pod-bogue1979-nats"
    buildmode: c-archive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
